server:
  port: 8889 # 指定 Eureka 实例的端口号

eureka:
  instance:
    prefer-ip-address: true # 是否显示主机的IP
  client:
    #    register-with-eureka: false # 拒绝向自己注册自己
    #    fetch-registry: false # 不需要检索服务
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 指定 Eureka 服务端地址
spring:
  application:
    name: ms-ilvc-config-server # 指定应用名称
  profiles:
#    active: native # 使用本地文件系统的存储方式来保存配置信息
  cloud:
    config:
      server:
        git:
#        native: 本地存储
#          search-locations: classpath:/config
          uri:  https://github.com/lvcAI/ms-ilvc-demo
          search-paths: config/

